---
title: "usps_network"
author: "Nathaniel Richardson"
date: "February 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(readr)
require(dplyr)
require(ggplot2)
```

```{r}
usps <- read.csv("usps_digit_recognizer.csv")
```




```{r}

softmax <- function (h) {
  exp(h) / apply(exp(h), 1, sum)
}
   
cross_entropy <- function(Y, P) {
  -sum(Y*log(P))
}

accuracy <- function (Y, P) {
  val <- c()
  for (i in 1:length(Y) / 10) {
    suppressWarnings(tryCatch({
      val[i] <-as.numeric((which(Y[i, ] == max(Y[i, ]))) == (which(P[i, ] == max(P[i, ]))))
  }, error = function(e) {
  val[i] <- 0
  }))
  
  }
  acc <- (sum(val) / length(val))
}

sigmoid <- function(H) 1/(1+exp(-H))

feed_forward <- function(X, W1, b1,W2,b2,W3, b3){ #,W4,b4,W5, b5) {
    
    Z1 <- sigmoid((X%*%W1) +b1)
    Z2 <- sigmoid((Z1%*%W2)+b2)
    #Z3 <- sigmoid((Z2%*%W3)+b3)
    #Z4 <- sigmoid((Z3%*%W4)+b4)
    P <- softmax((Z2%*%W3)+b3)
    return(list(Z1,Z2,P))
}
```

```{r}
one_hot_encoding <- function(x){
  
N = length(x)
K = length(unique(x))
u <- sort(unique(x), decreasing = FALSE)
ind =1
q <-c()
encoded_df <- data_frame("1" <-  c(1:K))

for (i in x){
  count = 1
  for (c in u){
    if (x[ind] == u[count]){
      q <- rep(0, times = K)
      q[count] <- 1
      encoded_df[ind] <- q
    }
    count = count+1
  }
  ind = ind+1
} 
encoded_df <- t(encoded_df)

}
```


```{r}
Y <- one_hot_encoding(usps$label)
```

```{r}
X <- usps %>%
  select(
    -label
    )
X <- X/255
```


```{r}
X_cross <-  X[2:707]*X[3:708]
```

```{r}
X<-cbind(X, X_cross)
```

```{r}
X_cross2 <-  X[2:680]*X[30:708]
```

```{r}
X<-cbind(X, X_cross2)
```

```{r}
 EX <- data_frame(X[1])
 ind =1
  for (i in 1:length(X))
  {
    if (sum(X[i])!=0){
      EX[ind] <- X[i]
      ind = ind+1
    }
  }
 X<- EX
 
```

```{r}
Y_t <- as.matrix(Y[1:25200,])
Phi_t <- as.matrix(X[1:25200,])
```

```{r}
Y_v <- as.matrix(Y[25200:33600,])
Phi_v <- as.matrix(X[25200:33600,])
```

```{r}

M1 = 17
M2 = 17


W1 = t(replicate(dim(Phi_t)[2], rnorm(M1)))
b1 = rnorm(M1)
W2 = t(replicate(M1, rnorm(M2)))
b2 = rnorm(M2)
W3 = t(replicate(M2, rnorm(dim(Y_t)[2])))
b3 = rnorm(dim(Y_t)[2])
```


```{r}
J = c()
eta = 1e-4
epochs = 4e2
en = c()


for (i in 1:epochs){
    l <- suppressWarnings(feed_forward(Phi_t, W1, b1,W2,b2,W3, b3))
    Z1 <- l[[1]]
    Z2 <- l[[2]]
    
  
    P_t <- l[[3]]
    J[i] <- (cross_entropy(Y_t,P_t)) 
    
    dH3 = as.matrix(P_t-Y_t)
    dW3 = t(Z2)%*% dH3
    W3  = W3- eta*dW3
    b3  = b3- eta* apply(dH3, 1, sum)
    
    dZ2 = dH3 %*% t(W3)
    dH2 = dZ2*Z2 * (1-Z2)
    dW2 = t(Z1) %*% dH2
    W2  = W2 - eta*dW2
    b2 = b2 - eta* apply(dH2, 1, sum)
    
    dZ1 = dH2%*%t(W2)
    dH1 = dZ1*Z1 * (1-Z1)
    dW1 = t(Phi_t) %*% dH1
    W1 = W1- eta* dW1
    b1 = b1- eta*apply(dH1,1, sum) 
    
    en[i] <- i
    
    if(i%%50==0){
      P_v <- suppressWarnings(feed_forward(Phi_v, W1, b1,W2,b2,W3, b3)[[3]])
      acc_v <- accuracy(Y_v,P_v)
      acc <- accuracy(Y_t,P_t)
     print(paste0("Epoch: ", i, " | Accuracy Train: %", signif(acc*100, digits = 4), " Accuracy Val: %", signif(acc_v*100, digits = 4)))
     
    }
}
```


```{r}
# 5 neurons at 400 epochs yeilds 63.53 nad 57.01
#10 neurons at 400 epochs yeilds 79.9 and 66.21
#15 neurons at 400 epochs yeilds 86.36 and 77.18
#20 neurons at 400 epochs yeilds 63.73 and 55.89
#17 neurons at 400 epochs yeilds 86.25 and 77.37

#choose 17 neurons to be the best

```

```{r}
eta = 1e-4
epochs = 3e2
acc_cv<- c(0)
lam2 <- c(1)
ind = 1
index <- c()


for (l2 in 1:5){
M1 = 17
M2 = 17

W1 = t(replicate(dim(Phi_t)[2], rnorm(M1)))
b1 = rnorm(M1)
W2 = t(replicate(M1, rnorm(M2)))
b2 = rnorm(M2)
W3 = t(replicate(M2, rnorm(dim(Y_t)[2])))
b3 = rnorm(dim(Y_t)[2])

  for (i in 1:epochs){
      l <- suppressWarnings(feed_forward(Phi_t, W1, b1,W2,b2,W3, b3))
      Z1 <- l[[1]]
      Z2 <- l[[2]]
      P_t <- l[[3]]
      P_v <- suppressWarnings(feed_forward(Phi_v, W1, b1,W2,b2,W3, b3)[[3]])
    
      dH3 = as.matrix(P_t-Y_t)
      dW3 = t(Z2)%*% dH3
      W3  = W3- eta*(dW3 + (5*l2)*W3)
      b3  = b3- eta* apply(dH3, 1, sum)
    
      dZ2 = dH3 %*% t(W3)
      dH2 = dZ2*Z2 * (1-Z2)
      dW2 = t(Z1) %*% dH2
      W2  = W2 - eta*(dW2+ (5*l2)*W2 )
      b2 = b2 - eta* apply(dH2, 1, sum)
    
      dZ1 = dH2%*%t(W2)
      dH1 = dZ1*Z1 * (1-Z1)
      dW1 = t(Phi_t) %*% dH1
      W1 = W1- eta*(dW1+ (5*l2)*W1)
      b1 = b1- eta*apply(dH1,1, sum) 
    
      lam2[ind] <-l2
      acc_cv[ind] <- accuracy(Y_v,P_v)
      index[ind] <- ind
      ind = ind +1
    
    
    if(i%%50==0){
      
      acc_v <- accuracy(Y_v,P_v)
      acc <- accuracy(Y_t,P_t)
     print(paste0("l2: ", l2*5, " | Epoch: ", i, " | Accuracy Train: %", signif(acc*100, digits = 4),
                  " | Accuracy Val: %", signif(acc_v*100, digits = 4)))
     
    }
  }
}
```

```{r}
#l2 of  0 at 300 epochs gives 83.85 and 73.91
#l2 of  5 at 300 epochs gives 84.61 and 76.94
#l2 of 10 at 300 epochs gives 84.36 and 80.12
#l2 of 15 at 250 epochs gives 84.15 and 69.16

#choose 10 to be best l2
```

```{r}

M1 = 17
M2 = 17


W1 = t(replicate(dim(Phi_t)[2], rnorm(M1)))
b1 = rnorm(M1)
W2 = t(replicate(M1, rnorm(M2)))
b2 = rnorm(M2)
W3 = t(replicate(M2, rnorm(dim(Y_t)[2])))
b3 = rnorm(dim(Y_t)[2])
```

```{r}
J = c()
eta = 1e-4
epochs = 4e3
en = c()
lam2 = 10

for (i in 1:epochs){
    l <- suppressWarnings(feed_forward(Phi_t, W1, b1,W2,b2,W3, b3))
    Z1 <- l[[1]]
    Z2 <- l[[2]
    P_t <- l[[3]]
    J[i] <- (cross_entropy(Y_t,P_t)) 
    
    dH3 = as.matrix(P_t-Y_t)
    dW3 = t(Z2)%*% dH3
    W3  = W3- eta*(dW3+W3*lam2)
    b3  = b3- eta* apply(dH3, 1, sum)
    
    dZ2 = dH3 %*% t(W3)
    dH2 = dZ2*Z2 * (1-Z2)
    dW2 = t(Z1) %*% dH2
    W2  = W2 - eta*(dW2+W2*lam2)
    b2 = b2 - eta* apply(dH2, 1, sum)
    
    dZ1 = dH2%*%t(W2)
    dH1 = dZ1*Z1 * (1-Z1)
    dW1 = t(Phi_t) %*% dH1
    W1 = W1- eta* (dW1+W1*lam2)
    b1 = b1- eta*apply(dH1,1, sum) 
    
    en[i] <- i
    
    if(i%%150==0){
      P_v <- suppressWarnings(feed_forward(Phi_v, W1, b1,W2,b2,W3, b3)[[3]])
      acc_v <- accuracy(Y_v,P_v)
      acc <- accuracy(Y_t,P_t)
     print(paste0("Epoch: ", i, " | Accuracy Train: %", signif(acc*100, digits = 4), " Accuracy Val: %", signif(acc_v*100, digits = 4)))
     
    }
    
    
}
```

```{r}
plot(x=en,y=J)
J_plot <- data.frame(
  "epochs" = en,
   "J" = J
 )
```

```{r}
P_v <- suppressWarnings(feed_forward(Phi_v, W1, b1,W2,b2,W3, b3)[[3]])
acc_v <- accuracy(Y_v,P_v)
print(paste0("Accuracy: %", signif(acc_v*100, digits = 4)))
```

```{r}
Y_test <- as.matrix(Y[33600:42000,])
Phi_test <- as.matrix(X[33600:42000,])
```

```{r}
P_test <- suppressWarnings(feed_forward(Phi_test, W1, b1,W2,b2,W3, b3)[[3]])

acc_v <- accuracy(Y_test,P_test)
print(paste0("Accuracy: %", signif(acc_v*100, digits = 4)))
```
